chore(feat/install-script): started working in the install script

diff --git a/startup/functions b/startup/functions
--- a/startup/functions
+++ b/startup/functions
@@ -3,27 +3,33 @@
 echo "Setting up message functions..."
 
 WORKSPACE_PATH=~/ws
-MC_DOTFILES_PATH=~/.mcustiel
+export MC_DOTFILES_PATH=~/.mcustiel
 
 CHECK="\xE2\x9C\x94"
 CROSS="\xE2\x9D\x8C\x0A"
+ANSI_OPEN="\033["
 
 function resetcolors {
-    echo -n -e "\033[0m"
+    echo -n -e "${ANSI_OPEN}0m"
 }
 
 function importantmsg {
-    echo -e "\033[1m$1"
+    echo -e "${ANSI_OPEN}1m$1"
     resetcolors
 }
 
 function errormsg {
-    echo -e "\033[91m$1"
+    echo -e "${ANSI_OPEN}91m$1"
     resetcolors
 }
 
 function infomsg {
-    echo -e "\033[94m$1"
+    echo -e "${ANSI_OPEN}94m$1"
+    resetcolors
+}
+
+function warnmsg {
+    echo -e "${ANSI_OPEN}93m$1"
     resetcolors
 }
 
@@ -33,38 +39,38 @@ function msg {
 }
 
 function successmsg {
-    echo -e "\033[92m$1"
+    echo -e "${ANSI_OPEN}92m$1"
     resetcolors
 }
 
 msg "Setting up general functions..."
 
 function cdws {
-    cd $WORKSPACE_PATH/$1
+    cd "$WORKSPACE_PATH/$1" || { echo "Directory not found"l; exit 1; }
 }
 
 function gpuob {
-    git push -u origin $(git rev-parse --abbrev-ref HEAD)
+    git push -u origin "$(git rev-parse --abbrev-ref HEAD)"
 }
 
 function gdcommits {
-   git log --graph --pretty=format:'%C(bold)%h%Creset%C(magenta)%d%Creset %s %C(yellow)<%an> %C(cyan)(%cr)%Creset' --abbrev-commit --date=relative $(git symbolic-ref --short HEAD)..$1
+   git log --graph --pretty=format:'%C(bold)%h%Creset%C(magenta)%d%Creset %s %C(yellow)<%an> %C(cyan)(%cr)%Creset' --abbrev-commit --date=relative "$(git symbolic-ref --short HEAD)".."$1"
 }
 
 function mdcd {
-    mkdir $1 && cd $1
+    { test mkdir "$1"; cd "$1"; } || { echo "Operation failed"; exit 1; }
 }
 
 function mvip {
-    mv $1 $(realpath $(dirname $1))/$2
+    mv "$1" "$(realpath "$(dirname "$1")")/$2"
 }
 
 function cpip {
-    cp $1 $(realpath $(dirname $1))/$2
+    cp "$1" "$(realpath "$(dirname "$1")")/$2"
 }
 
 function cpipr {
-    cp -r $1 $(realpath $(dirname $1))/$2
+    cp -r "$1" "$(realpath "$(dirname "$1")")/$2"
 }
 
 successmsg "Functions done. ${CHECK}"
